//Number Guess Game
// This guess the number game is a short TypeScript/Node.js project that allows the user to guess 
// the number generated by the computer. There are also several ways to alter the game, like adding 
// more rounds or displaying the score. It’s quite simple and uses the random function to generate a number.

import inquirer from "inquirer";

async function startFunc(){
    const systemNum = Math.floor(Math.random() * 100+1);
    const userNum = await inquirer.prompt([
      {type: "number",
       name: "userguess",
       message: "Enter the number between 1 to 100",
      }
    ]);
    const {userguess} = userNum;
    console.log(`Your Guess ${userguess} System Guess ${systemNum}`);

    if (userguess === systemNum){
        console.log("The Guess Number is correct! you win");
    }
    else{
        console.log("The Guess Number is not correct");
    }
}

async function startAgain(){
    do{
        await startFunc();
        var again = await inquirer.prompt({
                type: "input",
                name: "restart",
                message: "Do you want to continue? Press Y or N",
    })
    }
 while (again.restart == "Y" || again.restart == "y" || again.restart == "YES" || again.restart == "yes")
}
 startAgain();

